name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: every new commit on this PR
        run: echo "test will be executed by every commits on this PR" # Put test code here
